#!/bin/bash
numtests=25
command="./../hw5 < t\$i.in >& t\$i.res"
i="1"
while [ $i -le $numtests ]
	do
	eval $command
	diff t$i.res res$i.out &> /dev/null
	if [[ $? != 0 ]]
		then
		echo "Failed test #"$i"!"
		exit
	fi
	i=$[$i+1]
done